name: build-push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set short
        run: echo "short=${GITHUB_REF##*/}" >> "${GITHUB_ENV}"
      - name: Set tag
        run: echo "tag=${short/master/latest}" >> "${GITHUB_ENV}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: robertdebock/docker-cntlm:${{ env.tag }}
